### ISSUE TITLE
Tests are hanging with new testerina migration

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/ballerina-standard-library#3536]
**Description:**

> $Subject

**Steps to reproduce:**

Build `testerina-migration` branch locally and use that as the lang version to build HTTP module

**Affected Versions:**

Ballerina SwanLake 2201.3.0

**Comment by TharmiganK** [comment]
**Issue :** 

Tests are hanging when the resource function returns an error.

```ballerina
import ballerina/http;
import ballerina/test;

service / on new http:Listener(9090) {
    resource function post postEndPoint() returns string|error {
        return error http:Error("Manual error");
    }
}

@test:Config {}
function test1() {
    http:Client participantEP = checkpanic new ("http://localhost:9090/postEndPoint");
    http:Request req = new;
    http:Response|error response = participantEP->post("", req);
    if (response is http:Response) {
        test:assertEquals(response.statusCode, 500, msg = "Response code mismatched");
        test:assertEquals(response.getTextPayload(), "Manual error");
    }
}
```

**Reason :**

When the resource returns an error, the `DefaultErrorInterceptor` is got involved. Since we return a HTTP error response from the interceptor this creates two futures but only the last one is complete. Since the previous futures are not complete the tests are hanging forever with the new testerina implementation.

Flow : 
1. CallableUnitCallBack : returns an error 
2. ballerina:`returnErrorResponse` is called
3. `nativeRespondError` is called : a future is created
4. ResponseInterceptorCallBack : returns a 500 Internal Error Response
5. This calls again `returnResponse`
6. `nativeRespond` is called : another future is created
7. Last one is closed but not the first one

Same can happen if we have multiple response interceptors and return values rather than calling `ctx.next()`

```ballerina
import ballerina/http;
import ballerina/test;

service class ResponseInterceptor {
    *http:ResponseInterceptor;
    final string returnValue;

    function init(string returnValue) {
        self.returnValue = returnValue;
    }

	remote function interceptResponse(http:RequestContext ctx) returns string {
		return self.returnValue;
	}
}

@http:ServiceConfig {
    interceptors: [
      new ResponseInterceptor("Hello from Response Interceptor 3"), 
      new ResponseInterceptor("Hello from Response Interceptor 2"), 
      new ResponseInterceptor("Hello from Response Interceptor 1")
    ]
}
service / on new http:Listener(9090) {
    resource function post postEndPoint() returns string|error {
        return "Hello World!";
    }
}

@test:Config {}
function test1() {
    http:Client participantEP = checkpanic new ("http://localhost:9090/postEndPoint");
    http:Request req = new;
    http:Response|error response = participantEP->post("", req);
    if (response is http:Response) {
        test:assertEquals(response.statusCode, 201, msg = "Response code mismatched");
        test:assertEquals(response.getTextPayload(), "Hello from Response Interceptor 3");
    }
}
```

**Comment by chamil321** [comment]
Fixed via the attached PR

**Comment by TharmiganK** [comment]
Reopening the issue since the tests are still hanging with the new testerina implementation

**Comment by Dilhasha** [comment]
The test execution is still hanging 2201.4.0 onwards.

**Comment by TharmiganK** [comment]
> The test execution is still hanging 2201.4.0 onwards.

You are referring to the websub/websubhub questions in the hackathon right? That seems to be an issue with websub/websubhub module. See this issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/4019

@ayeshLK Have we found the root cause for this? Seems to be a critical bug

**Comment by Dilhasha** [comment]
> > The test execution is still hanging 2201.4.0 onwards.
> 
> You are referring to the websub/websubhub questions in the hackathon right? That seems to be an issue with websub/websubhub module. See this issue: #4019
> 
> @ayeshLK Have we found the root cause for this? Seems to be a critical bug

Yes, we can close this issue as it is tracked in https://github.com/ballerina-platform/ballerina-standard-library/issues/4019
